project:
  type: website

execute:
  freeze: auto

lang: pt-BR

website:
  title: "Mar Selvagem"
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - text: "More"
        menu: 
          - presentations.qmd
          - demo/demo.qmd
          - about.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true



